import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleTagManager } from '@next/third-parties/google'
import FloatingWhatsAppRedirect from "./components/FloatingWhatsAppRedirect";
import { whatsappChatLink } from "@/constants";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Al Habib Travel LTD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleTagManager gtmId="GTM-TXMKX3NK" />
        {children}
        <FloatingWhatsAppRedirect whatsappLink={whatsappChatLink} />
      </body>
    </html>
  );
}
